### ISSUE TITLE
rtl8821ae driver breaks 4.10.8 kernel

### ISSUE THREAD

**Issue by feckah** [lwfinger/rtlwifi_new#229]
I'm using the 4.10.8 kernel with Ubuntu 16.04, and after installing the driver, the system becomes pretty much unusable(can't even load desktop in GNOME).

Here's what I found in syslog, starting from the driver errors to the entire system crash:

Edit: just seen #226 and it's probably the same issue.

> Apr  7 17:49:18 FeckaLaptop NetworkManager[1081]: <info>  [1491580158.7090] device (wlp2s0): supplicant interface state: associating -> 4-way handshake
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168005] wlp2s0: associated
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168011] IPv6: ADDRCONF(NETDEV_CHANGE): wlp2s0: link becomes ready
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168162] BUG: unable to handle kernel NULL pointer dereference at           (null)
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168189] IP:           (null)
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168200] PGD 15483e067 
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168201] PUD 157f2e067 
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168210] PMD 0 
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168218] 
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168231] Oops: 0010 [#1] SMP
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168242] Modules linked in: rfcomm xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack libcrc32c bbswitch(OE) xt_tcpudp bridge stp bnep llc iptable_filter ip_tables x_tables 8250_dw snd_hda_codec_hdmi snd_hda_codec_realtek snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep arc4 intel_rapl snd_pcm snd_seq_midi snd_seq_midi_event snd_rawmidi x86_pkg_temp_thermal intel_powerclamp kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel snd_seq pcbc snd_seq_device snd_timer uvcvideo videobuf2_vmalloc videobuf2_memops aesni_intel videobuf2_v4l2 videobuf2_core aes_x86_64 idma64 crypto_simd virt_dma glue_helper cryptd rtl8821ae(OE) btcoexist(OE) rtl_pci(OE) rtlwifi(OE) intel_cstate videodev
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168453]  intel_lpss_pci mac80211 intel_rapl_perf snd input_leds cfg80211 joydev soundcore serio_raw hci_uart media btqca binfmt_misc btusb btrtl btbcm btintel mei_me bluetooth mei shpchp intel_pch_thermal ucsi ideapad_laptop sparse_keymap wmi intel_lpss_acpi mac_hid tpm_crb intel_lpss acpi_pad coretemp parport_pc ppdev lp parport autofs4 hid_generic usbhid i915 psmouse i2c_algo_bit drm_kms_helper nvme nvme_core syscopyarea sysfillrect sysimgblt fb_sys_fops r8169 ahci mii drm libahci video pinctrl_sunrisepoint pinctrl_intel i2c_hid hid fjes [last unloaded: nvidia]
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168600] CPU: 1 PID: 51 Comm: kworker/u8:1 Tainted: P        W  OE   4.10.8-041008-generic #201703310531
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168623] Hardware name: LENOVO 80RU/Lenovo ideapad 700-15ISK, BIOS E5CN56WW 09/29/2016
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168659] Workqueue: phy0 ieee80211_iface_work [mac80211]
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168675] task: ffff908b591dc500 task.stack: ffff9fdcc085c000
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168690] RIP: 0010:          (null)
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168700] RSP: 0018:ffff9fdcc085fc88 EFLAGS: 00010246
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168714] RAX: ffffffffc1732620 RBX: 0000000000000000 RCX: 0000000000000000
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168731] RDX: 0000000000000000 RSI: ffff9fdcc085fc97 RDI: ffff908b56381520
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168749] RBP: ffff9fdcc085fcb8 R08: 0000000000000000 R09: ffff908b4e61d400
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168766] R10: ffff908b56380720 R11: 0000000000000000 R12: ffff908b55d6f818
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168783] R13: ffff908b56381520 R14: 00000000ffffffa1 R15: ffff9fdcc085fd68
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168801] FS:  0000000000000000(0000) GS:ffff908b5ec80000(0000) knlGS:0000000000000000
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168822] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168836] CR2: 0000000000000000 CR3: 000000015137f000 CR4: 00000000003406e0
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168854] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168871] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168908] Call Trace:
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168919]  ? rtl_rx_agg_start+0x92/0xb0 [rtlwifi]
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168948]  rtl_op_ampdu_action+0x45/0x80 [rtlwifi]
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168969]  drv_ampdu_action+0x6f/0x170 [mac80211]
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.168990]  __ieee80211_start_rx_ba_session+0x395/0x610 [mac80211]
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.169013]  ieee80211_process_addba_request+0x5f/0x70 [mac80211]
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.169036]  ieee80211_iface_work+0x437/0x470 [mac80211]
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.169051]  process_one_work+0x1fc/0x4b0
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.169062]  worker_thread+0x4b/0x500
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.169073]  kthread+0x101/0x140
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.169083]  ? process_one_work+0x4b0/0x4b0
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.169095]  ? kthread_create_on_node+0x60/0x60
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.169108]  ret_from_fork+0x2c/0x40
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.169118] Code:  Bad RIP value.
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.169130] RIP:           (null) RSP: ffff9fdcc085fc88
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.169143] CR2: 0000000000000000
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.175325] ---[ end trace 6469c63608b4b0bb ]---
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.194667] BUG: unable to handle kernel NULL pointer dereference at           (null)
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.194693] IP:           (null)
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.194703] PGD 0 
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.194704] 
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.194716] Oops: 0010 [#2] SMP
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.194726] Modules linked in: ccm rfcomm xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack libcrc32c bbswitch(OE) xt_tcpudp bridge stp bnep llc iptable_filter ip_tables x_tables 8250_dw snd_hda_codec_hdmi snd_hda_codec_realtek snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep arc4 intel_rapl snd_pcm snd_seq_midi snd_seq_midi_event snd_rawmidi x86_pkg_temp_thermal intel_powerclamp kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel snd_seq pcbc snd_seq_device snd_timer uvcvideo videobuf2_vmalloc videobuf2_memops aesni_intel videobuf2_v4l2 videobuf2_core aes_x86_64 idma64 crypto_simd virt_dma glue_helper cryptd rtl8821ae(OE) btcoexist(OE) rtl_pci(OE) rtlwifi(OE) intel_cstate
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.194912]  videodev intel_lpss_pci mac80211 intel_rapl_perf snd input_leds cfg80211 joydev soundcore serio_raw hci_uart media btqca binfmt_misc btusb btrtl btbcm btintel mei_me bluetooth mei shpchp intel_pch_thermal ucsi ideapad_laptop sparse_keymap wmi intel_lpss_acpi mac_hid tpm_crb intel_lpss acpi_pad coretemp parport_pc ppdev lp parport autofs4 hid_generic usbhid i915 psmouse i2c_algo_bit drm_kms_helper nvme nvme_core syscopyarea sysfillrect sysimgblt fb_sys_fops r8169 ahci mii drm libahci video pinctrl_sunrisepoint pinctrl_intel i2c_hid hid fjes [last unloaded: nvidia]
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.195032] CPU: 3 PID: 670 Comm: kworker/3:4 Tainted: P      D W  OE   4.10.8-041008-generic #201703310531
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.195054] Hardware name: LENOVO 80RU/Lenovo ideapad 700-15ISK, BIOS E5CN56WW 09/29/2016
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.195077] Workqueue: rtl8821ae_pci rtl_watchdog_wq_callback [rtlwifi]
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.195092] task: ffff908b50d08000 task.stack: ffff9fdcc4830000
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.195106] RIP: 0010:          (null)
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.195116] RSP: 0018:ffff9fdcc4833de0 EFLAGS: 00010202
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.195129] RAX: ffffffffc1732620 RBX: ffff908b56380720 RCX: 0000000000000002
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.195145] RDX: 0000000000000002 RSI: ffff908b5ed98a60 RDI: ffff908b56381520
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.195162] RBP: ffff9fdcc4833e48 R08: 0000000000000000 R09: ffff908b5638b5e4
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.196338] R10: 0000000000000000 R11: 0000000000000000 R12: ffff908b56381520
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.197534] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.198795] FS:  0000000000000000(0000) GS:ffff908b5ed80000(0000) knlGS:0000000000000000
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.199981] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.201193] CR2: 0000000000000000 CR3: 0000000089e09000 CR4: 00000000003406e0
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.202392] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.203703] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.204852] Call Trace:
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.205978]  ? rtl_watchdog_wq_callback+0x443/0x480 [rtlwifi]
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.207167]  process_one_work+0x1fc/0x4b0
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.208229]  worker_thread+0x4b/0x500
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.209259]  kthread+0x101/0x140
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.210252]  ? process_one_work+0x4b0/0x4b0
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.211281]  ? kthread_create_on_node+0x60/0x60
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.212238]  ret_from_fork+0x2c/0x40
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.213174] Code:  Bad RIP value.
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.214094] RIP:           (null) RSP: ffff9fdcc4833de0
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.215096] CR2: 0000000000000000
> Apr  7 17:49:18 FeckaLaptop kernel: [   12.216022] ---[ end trace 6469c63608b4b0bc ]---
> Apr  7 17:49:21 FeckaLaptop NetworkManager[1081]: <info>  [1491580161.5483] manager: WiFi hardware radio set enabled
> Apr  7 17:49:21 FeckaLaptop NetworkManager[1081]: <info>  [1491580161.5483] manager: WWAN hardware radio set enabled
> Apr  7 17:49:21 FeckaLaptop org.gtk.vfs.Daemon[1498]: A connection to the bus can't be made
> Apr  7 17:49:21 FeckaLaptop systemd[1]: Created slice User Slice of fecka.
> Apr  7 17:49:21 FeckaLaptop systemd[1]: Starting User Manager for UID 1000...
> Apr  7 17:49:21 FeckaLaptop systemd[1]: Started Session c2 of user fecka.
> Apr  7 17:49:21 FeckaLaptop systemd[1746]: Reached target Paths.
> Apr  7 17:49:21 FeckaLaptop systemd[1746]: Reached target Sockets.
> Apr  7 17:49:21 FeckaLaptop systemd[1746]: Reached target Timers.
> Apr  7 17:49:21 FeckaLaptop systemd[1746]: Reached target Basic System.
> Apr  7 17:49:21 FeckaLaptop systemd[1746]: Reached target Default.
> Apr  7 17:49:21 FeckaLaptop systemd[1746]: Startup finished in 22ms.
> Apr  7 17:49:21 FeckaLaptop systemd[1]: Started User Manager for UID 1000.
> Apr  7 17:49:22 FeckaLaptop org.ayatana.bamf[1919]: bamfdaemon start/running, process 1981
> Apr  7 17:49:22 FeckaLaptop org.a11y.Bus[1919]: Activating service name='org.a11y.atspi.Registry'
> Apr  7 17:49:22 FeckaLaptop org.a11y.Bus[1919]: ** (process:2007): WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
> Apr  7 17:49:22 FeckaLaptop org.a11y.Bus[1919]: Successfully activated service 'org.a11y.atspi.Registry'
> Apr  7 17:49:22 FeckaLaptop org.a11y.atspi.Registry[2021]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
> Apr  7 17:49:23 FeckaLaptop org.gnome.ScreenSaver[1919]: ** (gnome-screensaver:2077): WARNING **: Couldn't get presence status: The name org.gnome.SessionManager was not provided by any .service files
> Apr  7 17:49:23 FeckaLaptop gnome-session[2056]: gnome-session-binary[2056]: WARNING: Could not parse desktop file shutter.desktop or it references a not found TryExec binary
> Apr  7 17:49:23 FeckaLaptop gnome-session-binary[2056]: WARNING: Could not parse desktop file shutter.desktop or it references a not found TryExec binary
> Apr  7 17:49:23 FeckaLaptop gnome-session[2056]: gnome-session-binary[2056]: WARNING: Could not parse desktop file indicator-printers.desktop or it references a not found TryExec binary
> Apr  7 17:49:23 FeckaLaptop gnome-session-binary[2056]: WARNING: Could not parse desktop file indicator-printers.desktop or it references a not found TryExec binary
> Apr  7 17:49:23 FeckaLaptop gnome-session[2056]: gnome-session-binary[2056]: WARNING: Could not parse desktop file update-notifier.desktop or it references a not found TryExec binary
> Apr  7 17:49:23 FeckaLaptop gnome-session-binary[2056]: WARNING: Could not parse desktop file update-notifier.desktop or it references a not found TryExec binary
> Apr  7 17:49:23 FeckaLaptop gnome-session[2056]: gnome-session-binary[2056]: WARNING: Could not parse desktop file onboard-autostart.desktop or it references a not found TryExec binary
> Apr  7 17:49:23 FeckaLaptop gnome-session-binary[2056]: WARNING: Could not parse desktop file onboard-autostart.desktop or it references a not found TryExec binary
> Apr  7 17:49:23 FeckaLaptop rtkit-daemon[1612]: Successfully made thread 2085 of process 2085 (n/a) owned by '1000' high priority at nice level -11.
> Apr  7 17:49:23 FeckaLaptop rtkit-daemon[1612]: Supervising 4 threads of 2 processes of 2 users.
> Apr  7 17:49:23 FeckaLaptop gnome-session[2056]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
> Apr  7 17:49:23 FeckaLaptop gnome-session[2056]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
> Apr  7 17:49:23 FeckaLaptop gnome-session[2056]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
> Apr  7 17:49:23 FeckaLaptop rtkit-daemon[1612]: Supervising 4 threads of 2 processes of 2 users.
> Apr  7 17:49:23 FeckaLaptop rtkit-daemon[1612]: Successfully made thread 2098 of process 2085 (n/a) owned by '1000' RT at priority 5.
> Apr  7 17:49:23 FeckaLaptop rtkit-daemon[1612]: Supervising 5 threads of 2 processes of 2 users.
> Apr  7 17:49:23 FeckaLaptop rtkit-daemon[1612]: Supervising 5 threads of 2 processes of 2 users.
> Apr  7 17:49:23 FeckaLaptop rtkit-daemon[1612]: Successfully made thread 2099 of process 2085 (n/a) owned by '1000' RT at priority 5.
> Apr  7 17:49:23 FeckaLaptop rtkit-daemon[1612]: Supervising 6 threads of 2 processes of 2 users.
> Apr  7 17:49:23 FeckaLaptop bluetoothd[981]: Endpoint registered: sender=:1.71 path=/MediaEndpoint/A2DPSource
> Apr  7 17:49:23 FeckaLaptop bluetoothd[981]: Endpoint registered: sender=:1.71 path=/MediaEndpoint/A2DPSink
> Apr  7 17:49:23 FeckaLaptop pulseaudio[2085]: [pulseaudio] backend-ofono.c: Failed to register as a handsfree audio agent with ofono: org.freedesktop.DBus.Error.ServiceUnknown: The name org.ofono was not provided by any .service files
> Apr  7 17:49:23 FeckaLaptop bluetoothd[981]: RFCOMM server failed for Headset Voice gateway: rfcomm_bind: Address already in use (98)
> Apr  7 17:49:23 FeckaLaptop rtkit-daemon[1612]: Successfully made thread 2101 of process 2101 (n/a) owned by '1000' high priority at nice level -11.
> Apr  7 17:49:23 FeckaLaptop rtkit-daemon[1612]: Supervising 7 threads of 3 processes of 2 users.
> Apr  7 17:49:23 FeckaLaptop pulseaudio[2101]: [pulseaudio] pid.c: Daemon already running.
> Apr  7 17:49:23 FeckaLaptop dbus[1026]: [system] Activating via systemd: service name='org.freedesktop.locale1' unit='dbus-org.freedesktop.locale1.service'
> Apr  7 17:49:23 FeckaLaptop systemd[1]: Starting Locale Service...
> Apr  7 17:49:23 FeckaLaptop gnome-session[2056]: current session already has an ibus-daemon.
> Apr  7 17:49:24 FeckaLaptop org.gnome.OnlineAccounts[1919]: goa-daemon-Message: goa-daemon version 3.18.3 starting
> Apr  7 17:49:24 FeckaLaptop dbus[1026]: [system] Activating via systemd: service name='org.freedesktop.GeoClue2' unit='geoclue.service'
> Apr  7 17:49:24 FeckaLaptop systemd[1]: Starting Location Lookup Service...
> Apr  7 17:49:24 FeckaLaptop dbus[1026]: [system] Activating via systemd: service name='org.freedesktop.UDisks2' unit='udisks2.service'
> Apr  7 17:49:24 FeckaLaptop systemd[1]: Starting Disk Manager...
> Apr  7 17:49:24 FeckaLaptop udisksd[2177]: udisks daemon version 2.1.7 starting
> Apr  7 17:49:24 FeckaLaptop dbus[1026]: [system] Successfully activated service 'org.freedesktop.UDisks2'
> Apr  7 17:49:24 FeckaLaptop systemd[1]: Started Disk Manager.
> Apr  7 17:49:24 FeckaLaptop udisksd[2177]: Acquired the name org.freedesktop.UDisks2 on the system message bus
> Apr  7 17:49:24 FeckaLaptop org.gtk.vfs.AfcVolumeMonitor[1919]: Volume monitor alive
> \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\...

**Comment by lwfinger** [comment]
The traceback on the error does not make much sense on my system. While in the rtlwifi_new directory, please run the following and post the terminal output:

gdb rtlwifi.ko
list *rtl_op_ampdu_action+0x45

**Comment by feckah** [comment]
It isn't much more informative apparently, (I cloned the current rtlwifi_new.git):

```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rtlwifi.ko...(no debugging symbols found)...done.
(gdb) list *rtl_op_ampdu_action+0x45
No symbol table is loaded.  Use the "file" command.
```

**Comment by lwfinger** [comment]
Your system is compiled with no symbols, thus no help.

Assuming that my improbable traceback is actually correct, I have pushed a change that might help. Do another pull and test again.

**Comment by feckah** [comment]
Unfortunately it is still not working:

```
Apr  7 20:56:37 FeckaLaptop NetworkManager[1012]: <info>  [1491591397.5052] sup-iface[0x2299210,wlp2s0]: config: set interface ap_scan to 1
Apr  7 20:56:40 FeckaLaptop wpa_supplicant[1271]: wlp2s0: SME: Trying to authenticate with 00:0e:8f:40:7c:84 (SSID='FecNet' freq=2437 MHz)
Apr  7 20:56:40 FeckaLaptop kernel: [   12.036857] wlp2s0: authenticate with 00:0e:8f:40:7c:84
Apr  7 20:56:40 FeckaLaptop kernel: [   12.037176] wlp2s0: send auth to 00:0e:8f:40:7c:84 (try 1/3)
Apr  7 20:56:40 FeckaLaptop NetworkManager[1012]: <info>  [1491591400.5784] device (wlp2s0): supplicant interface state: inactive -> authenticating
Apr  7 20:56:40 FeckaLaptop wpa_supplicant[1271]: wlp2s0: Trying to associate with 00:0e:8f:40:7c:84 (SSID='FecNet' freq=2437 MHz)
Apr  7 20:56:40 FeckaLaptop kernel: [   12.139728] wlp2s0: send auth to 00:0e:8f:40:7c:84 (try 2/3)
Apr  7 20:56:40 FeckaLaptop kernel: [   12.141900] wlp2s0: authenticated
Apr  7 20:56:40 FeckaLaptop kernel: [   12.143607] wlp2s0: associate with 00:0e:8f:40:7c:84 (try 1/3)
Apr  7 20:56:40 FeckaLaptop wpa_supplicant[1271]: wlp2s0: Associated with 00:0e:8f:40:7c:84
Apr  7 20:56:40 FeckaLaptop NetworkManager[1012]: <info>  [1491591400.6833] device (wlp2s0): supplicant interface state: authenticating -> associating
Apr  7 20:56:40 FeckaLaptop wpa_supplicant[1271]: wlp2s0: CTRL-EVENT-REGDOM-CHANGE init=COUNTRY_IE type=COUNTRY alpha2=HU
Apr  7 20:56:40 FeckaLaptop kernel: [   12.147531] wlp2s0: RX AssocResp from 00:0e:8f:40:7c:84 (capab=0x1411 status=0 aid=2)
Apr  7 20:56:40 FeckaLaptop kernel: [   12.147759] wlp2s0: associated
Apr  7 20:56:40 FeckaLaptop kernel: [   12.147805] IPv6: ADDRCONF(NETDEV_CHANGE): wlp2s0: link becomes ready
Apr  7 20:56:40 FeckaLaptop NetworkManager[1012]: <info>  [1491591400.6886] device (wlp2s0): supplicant interface state: associating -> associated
Apr  7 20:56:40 FeckaLaptop kernel: [   12.151736] BUG: unable to handle kernel NULL pointer dereference at           (null)
Apr  7 20:56:40 FeckaLaptop kernel: [   12.151762] IP:           (null)
Apr  7 20:56:40 FeckaLaptop kernel: [   12.151772] PGD 0 
Apr  7 20:56:40 FeckaLaptop kernel: [   12.151773] 
Apr  7 20:56:40 FeckaLaptop kernel: [   12.151785] Oops: 0010 [#1] SMP
Apr  7 20:56:40 FeckaLaptop kernel: [   12.151806] Modules linked in: rfcomm xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack libcrc32c bbswitch(OE) xt_tcpudp bridge stp llc iptable_filter ip_tables bnep x_tables 8250_dw intel_rapl snd_hda_codec_hdmi arc4 snd_hda_codec_realtek snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep snd_pcm x86_pkg_temp_thermal intel_powerclamp kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel snd_seq_midi pcbc snd_seq_midi_event rtl8821ae(OE) snd_rawmidi btcoexist(OE) aesni_intel aes_x86_64 crypto_simd glue_helper cryptd rtl_pci(OE) snd_seq rtlwifi(OE) intel_cstate uvcvideo intel_rapl_perf snd_seq_device snd_timer videobuf2_vmalloc mac80211 videobuf2_memops videobuf2_v4l2 videobuf2_core
Apr  7 20:56:40 FeckaLaptop kernel: [   12.151970]  videodev media snd input_leds joydev idma64 virt_dma serio_raw cfg80211 soundcore intel_lpss_pci btusb btrtl hci_uart btbcm btqca btintel bluetooth mei_me mei intel_pch_thermal ucsi binfmt_misc ideapad_laptop sparse_keymap wmi intel_lpss_acpi intel_lpss tpm_crb mac_hid acpi_pad shpchp coretemp parport_pc ppdev lp parport autofs4 hid_generic usbhid i915 psmouse i2c_algo_bit drm_kms_helper nvme nvme_core syscopyarea sysfillrect sysimgblt fb_sys_fops r8169 mii ahci drm libahci video i2c_hid pinctrl_sunrisepoint hid pinctrl_intel fjes [last unloaded: nvidia]
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152108] CPU: 2 PID: 5 Comm: kworker/u8:0 Tainted: P        W  OE   4.10.8-041008-generic #201703310531
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152130] Hardware name: LENOVO 80RU/Lenovo ideapad 700-15ISK, BIOS E5CN56WW 09/29/2016
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152162] Workqueue: phy0 ieee80211_iface_work [mac80211]
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152176] task: ffff894919ba2e00 task.stack: ffffb1dc80698000
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152190] RIP: 0010:          (null)
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152200] RSP: 0018:ffffb1dc8069bc88 EFLAGS: 00010246
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152213] RAX: ffffffffc2f07620 RBX: 0000000000000000 RCX: 0000000000000000
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152229] RDX: 0000000000000000 RSI: ffffb1dc8069bc97 RDI: ffff894917c51520
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152245] RBP: ffffb1dc8069bcb8 R08: 0000000000000000 R09: ffff894912ab5a00
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152262] R10: ffff894917c50720 R11: 0000000000000000 R12: ffff89491296d818
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152278] R13: ffff894917c51520 R14: 00000000ffffffa1 R15: ffffb1dc8069bd68
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152295] FS:  0000000000000000(0000) GS:ffff89491ed00000(0000) knlGS:0000000000000000
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152313] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152327] CR2: 0000000000000000 CR3: 0000000107409000 CR4: 00000000003406e0
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152344] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152360] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152376] Call Trace:
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152387]  ? rtl_rx_agg_start+0x92/0xb0 [rtlwifi]
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152401]  rtl_op_ampdu_action+0x45/0x80 [rtlwifi]
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152419]  drv_ampdu_action+0x6f/0x170 [mac80211]
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152438]  __ieee80211_start_rx_ba_session+0x395/0x610 [mac80211]
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152459]  ieee80211_process_addba_request+0x5f/0x70 [mac80211]
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152480]  ieee80211_iface_work+0x437/0x470 [mac80211]
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152494]  process_one_work+0x1fc/0x4b0
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152505]  worker_thread+0x4b/0x500
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152515]  kthread+0x101/0x140
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152524]  ? process_one_work+0x4b0/0x4b0
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152535]  ? kthread_create_on_node+0x60/0x60
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152547]  ret_from_fork+0x2c/0x40
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152556] Code:  Bad RIP value.
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152567] RIP:           (null) RSP: ffffb1dc8069bc88
Apr  7 20:56:40 FeckaLaptop kernel: [   12.152580] CR2: 0000000000000000
Apr  7 20:56:40 FeckaLaptop kernel: [   12.158396] ---[ end trace 5145b29aed5d7504 ]---
Apr  7 20:56:40 FeckaLaptop NetworkManager[1012]: <info>  [1491591400.6943] device (wlp2s0): supplicant interface state: associated -> 4-way handshake
Apr  7 20:56:42 FeckaLaptop org.gtk.vfs.Daemon[1456]: A connection to the bus can't be made
Apr  7 20:56:42 FeckaLaptop systemd[1]: Created slice User Slice of fecka.
Apr  7 20:56:42 FeckaLaptop systemd[1]: Starting User Manager for UID 1000...
Apr  7 20:56:42 FeckaLaptop systemd[1]: Started Session c2 of user fecka.
Apr  7 20:56:42 FeckaLaptop systemd[1661]: Reached target Timers.
Apr  7 20:56:42 FeckaLaptop systemd[1661]: Reached target Sockets.
Apr  7 20:56:42 FeckaLaptop systemd[1661]: Reached target Paths.
Apr  7 20:56:42 FeckaLaptop systemd[1661]: Reached target Basic System.
Apr  7 20:56:42 FeckaLaptop systemd[1661]: Reached target Default.
Apr  7 20:56:42 FeckaLaptop systemd[1661]: Startup finished in 12ms.
Apr  7 20:56:42 FeckaLaptop systemd[1]: Started User Manager for UID 1000.
Apr  7 20:56:42 FeckaLaptop org.ayatana.bamf[1773]: bamfdaemon start/running, process 1837
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927428] BUG: unable to handle kernel NULL pointer dereference at           (null)
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927458] IP:           (null)
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927470] PGD 14e5e1067 
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927470] PUD 1582b9067 
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927479] PMD 0 
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927489] 
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927504] Oops: 0010 [#2] SMP
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927514] Modules linked in: ccm rfcomm xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack libcrc32c bbswitch(OE) xt_tcpudp bridge stp llc iptable_filter ip_tables bnep x_tables 8250_dw intel_rapl snd_hda_codec_hdmi arc4 snd_hda_codec_realtek snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep snd_pcm x86_pkg_temp_thermal intel_powerclamp kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel snd_seq_midi pcbc snd_seq_midi_event rtl8821ae(OE) snd_rawmidi btcoexist(OE) aesni_intel aes_x86_64 crypto_simd glue_helper cryptd rtl_pci(OE) snd_seq rtlwifi(OE) intel_cstate uvcvideo intel_rapl_perf snd_seq_device snd_timer videobuf2_vmalloc mac80211 videobuf2_memops videobuf2_v4l2 videobuf2_core
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927742]  videodev media snd input_leds joydev idma64 virt_dma serio_raw cfg80211 soundcore intel_lpss_pci btusb btrtl hci_uart btbcm btqca btintel bluetooth mei_me mei intel_pch_thermal ucsi binfmt_misc ideapad_laptop sparse_keymap wmi intel_lpss_acpi intel_lpss tpm_crb mac_hid acpi_pad shpchp coretemp parport_pc ppdev lp parport autofs4 hid_generic usbhid i915 psmouse i2c_algo_bit drm_kms_helper nvme nvme_core syscopyarea sysfillrect sysimgblt fb_sys_fops r8169 mii ahci drm libahci video i2c_hid pinctrl_sunrisepoint hid pinctrl_intel fjes [last unloaded: nvidia]
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927875] CPU: 1 PID: 526 Comm: kworker/1:5 Tainted: P      D W  OE   4.10.8-041008-generic #201703310531
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927898] Hardware name: LENOVO 80RU/Lenovo ideapad 700-15ISK, BIOS E5CN56WW 09/29/2016
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927923] Workqueue: rtl8821ae_pci rtl_watchdog_wq_callback [rtlwifi]
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927941] task: ffff89490d619700 task.stack: ffffb1dc80ef0000
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927956] RIP: 0010:          (null)
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927967] RSP: 0018:ffffb1dc80ef3de0 EFLAGS: 00010202
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927981] RAX: ffffffffc2f07620 RBX: ffff894917c50720 RCX: 0000000000000002
Apr  7 20:56:42 FeckaLaptop kernel: [   13.927999] RDX: 0000000000000002 RSI: ffff89491ec98a60 RDI: ffff894917c51520
Apr  7 20:56:42 FeckaLaptop kernel: [   13.928017] RBP: ffffb1dc80ef3e48 R08: 0000000000000000 R09: ffff894917c5b5e4
Apr  7 20:56:42 FeckaLaptop kernel: [   13.929363] R10: 0000000000000000 R11: 0000000000000000 R12: ffff894917c51520
Apr  7 20:56:42 FeckaLaptop kernel: [   13.930661] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
Apr  7 20:56:42 FeckaLaptop kernel: [   13.932039] FS:  0000000000000000(0000) GS:ffff89491ec80000(0000) knlGS:0000000000000000
Apr  7 20:56:42 FeckaLaptop kernel: [   13.933581] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Apr  7 20:56:42 FeckaLaptop kernel: [   13.934880] CR2: 0000000000000000 CR3: 000000014f20a000 CR4: 00000000003406e0
Apr  7 20:56:42 FeckaLaptop kernel: [   13.936339] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Apr  7 20:56:42 FeckaLaptop kernel: [   13.937785] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Apr  7 20:56:42 FeckaLaptop kernel: [   13.939255] Call Trace:
Apr  7 20:56:42 FeckaLaptop kernel: [   13.940635]  ? rtl_watchdog_wq_callback+0x443/0x480 [rtlwifi]
Apr  7 20:56:42 FeckaLaptop kernel: [   13.941833]  process_one_work+0x1fc/0x4b0
Apr  7 20:56:42 FeckaLaptop kernel: [   13.942891]  worker_thread+0x4b/0x500
Apr  7 20:56:42 FeckaLaptop kernel: [   13.944017]  kthread+0x101/0x140
Apr  7 20:56:42 FeckaLaptop kernel: [   13.945262]  ? process_one_work+0x4b0/0x4b0
Apr  7 20:56:42 FeckaLaptop kernel: [   13.946609]  ? kthread_create_on_node+0x60/0x60
Apr  7 20:56:42 FeckaLaptop kernel: [   13.947816]  ret_from_fork+0x2c/0x40
Apr  7 20:56:42 FeckaLaptop kernel: [   13.948979] Code:  Bad RIP value.
Apr  7 20:56:42 FeckaLaptop kernel: [   13.950164] RIP:           (null) RSP: ffffb1dc80ef3de0
Apr  7 20:56:42 FeckaLaptop kernel: [   13.951251] CR2: 0000000000000000
Apr  7 20:56:42 FeckaLaptop kernel: [   13.952316] ---[ end trace 5145b29aed5d7505 ]---
```

**Comment by lwfinger** [comment]
Pull again and try. This kind of debugging is not very satisfactory, but we seem not to have a choice.

**Comment by feckah** [comment]
Yeah, it's either hit or miss, thank you a lot for your efforts though!

It's still the same, the first trace isn't even related to your driver, but somehow it still is, as it doesn't show if the wifi driver isn't installed.

```
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679858] ------------[ cut here ]------------
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679861] WARNING: CPU: 0 PID: 1042 at /home/kernel/COD/linux/drivers/pci/pci.c:1641 pci_disable_device+0xa8/0xd0
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679862] pci 0000:01:00.0: disabling already-disabled device
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679862] Modules linked in: xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack libcrc32c bnep xt_tcpudp bbswitch(OE) bridge stp llc iptable_filter ip_tables x_tables 8250_dw snd_hda_codec_hdmi snd_hda_codec_realtek snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep snd_pcm snd_seq_midi snd_seq_midi_event intel_rapl x86_pkg_temp_thermal intel_powerclamp kvm irqbypass snd_rawmidi crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc snd_seq aesni_intel aes_x86_64 crypto_simd glue_helper cryptd arc4 intel_cstate snd_seq_device snd_timer intel_rapl_perf snd joydev input_leds serio_raw uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_core videodev rtl8821ae(OE) btcoexist(OE)
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679877]  rtl_pci(OE) rtlwifi(OE) mac80211 media soundcore cfg80211 mei_me idma64 virt_dma btusb intel_lpss_pci btrtl binfmt_misc mei hci_uart shpchp ideapad_laptop btbcm sparse_keymap btqca btintel bluetooth intel_pch_thermal ucsi wmi tpm_crb intel_lpss_acpi intel_lpss mac_hid acpi_pad coretemp parport_pc ppdev lp parport autofs4 hid_generic usbhid i915 psmouse i2c_algo_bit drm_kms_helper nvme nvme_core syscopyarea sysfillrect sysimgblt r8169 fb_sys_fops ahci mii drm libahci video i2c_hid pinctrl_sunrisepoint hid pinctrl_intel fjes [last unloaded: nvidia]
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679891] CPU: 0 PID: 1042 Comm: bumblebeed Tainted: P           OE   4.10.8-041008-generic #201703310531
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679891] Hardware name: LENOVO 80RU/Lenovo ideapad 700-15ISK, BIOS E5CN56WW 09/29/2016
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679892] Call Trace:
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679894]  dump_stack+0x63/0x81
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679895]  __warn+0xcb/0xf0
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679896]  warn_slowpath_fmt+0x5f/0x80
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679898]  ? pci_bus_write_config_word+0x1c/0x20
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679899]  ? __pci_set_master+0x6d/0xf0
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679900]  pci_disable_device+0xa8/0xd0
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679901]  bbswitch_off+0xad/0x240 [bbswitch]
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679902]  bbswitch_proc_write+0xb0/0xc7 [bbswitch]
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679904]  proc_reg_write+0x42/0x70
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679905]  __vfs_write+0x37/0x160
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679906]  ? apparmor_file_permission+0x18/0x20
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679908]  ? security_file_permission+0x3b/0xc0
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679909]  vfs_write+0xb5/0x1a0
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679910]  SyS_write+0x55/0xc0
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679911]  entry_SYSCALL_64_fastpath+0x1e/0xad
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679912] RIP: 0033:0x7f2f6c7306e0
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679912] RSP: 002b:00007fff11684708 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679913] RAX: ffffffffffffffda RBX: 000000000060c2f0 RCX: 00007f2f6c7306e0
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679914] RDX: 0000000000000028 RSI: 00000000012fa7c0 RDI: 0000000000000005
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679914] RBP: 00007fff116845a0 R08: 00007f2f6d664700 R09: 00000000012fa590
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679915] R10: 00007f2f6d664700 R11: 0000000000000246 R12: 00007f2f6d6661e0
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679915] R13: 0000000000000000 R14: 00007f2f6d692168 R15: 00007fff116845c8
Apr  7 22:12:56 FeckaLaptop kernel: [    7.679916] ---[ end trace a9f4ea469c6be1de ]---


Apr  7 22:12:59 FeckaLaptop NetworkManager[1029]: <info>  [1491595979.1888] Config: added 'ssid' value 'FecNet'
Apr  7 22:12:59 FeckaLaptop NetworkManager[1029]: <info>  [1491595979.1889] Config: added 'scan_ssid' value '1'
Apr  7 22:12:59 FeckaLaptop NetworkManager[1029]: <info>  [1491595979.1889] Config: added 'key_mgmt' value 'WPA-PSK'
Apr  7 22:12:59 FeckaLaptop NetworkManager[1029]: <info>  [1491595979.1889] Config: added 'psk' value '<omitted>'
Apr  7 22:12:59 FeckaLaptop NetworkManager[1029]: <info>  [1491595979.1898] sup-iface[0x13600b0,wlp2s0]: config: set interface ap_scan to 1
Apr  7 22:13:02 FeckaLaptop wpa_supplicant[1379]: wlp2s0: SME: Trying to authenticate with 00:0e:8f:40:7c:84 (SSID='FecNet' freq=2437 MHz)
Apr  7 22:13:02 FeckaLaptop wpa_supplicant[1379]: wlp2s0: Trying to associate with 00:0e:8f:40:7c:84 (SSID='FecNet' freq=2437 MHz)
Apr  7 22:13:02 FeckaLaptop kernel: [   13.751433] wlp2s0: authenticate with 00:0e:8f:40:7c:84
Apr  7 22:13:02 FeckaLaptop kernel: [   13.751759] wlp2s0: send auth to 00:0e:8f:40:7c:84 (try 1/3)
Apr  7 22:13:02 FeckaLaptop kernel: [   13.754021] wlp2s0: authenticated
Apr  7 22:13:02 FeckaLaptop kernel: [   13.754233] wlp2s0: associate with 00:0e:8f:40:7c:84 (try 1/3)
Apr  7 22:13:02 FeckaLaptop NetworkManager[1029]: <info>  [1491595982.2775] device (wlp2s0): supplicant interface state: inactive -> associating
Apr  7 22:13:02 FeckaLaptop kernel: [   13.757721] wlp2s0: RX AssocResp from 00:0e:8f:40:7c:84 (capab=0x1411 status=0 aid=2)
Apr  7 22:13:02 FeckaLaptop wpa_supplicant[1379]: wlp2s0: Associated with 00:0e:8f:40:7c:84
Apr  7 22:13:02 FeckaLaptop wpa_supplicant[1379]: wlp2s0: CTRL-EVENT-REGDOM-CHANGE init=COUNTRY_IE type=COUNTRY alpha2=HU
Apr  7 22:13:02 FeckaLaptop NetworkManager[1029]: <info>  [1491595982.2910] device (wlp2s0): supplicant interface state: associating -> 4-way handshake
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765139] wlp2s0: associated
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765145] IPv6: ADDRCONF(NETDEV_CHANGE): wlp2s0: link becomes ready
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765262] BUG: unable to handle kernel NULL pointer dereference at           (null)
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765288] IP:           (null)
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765298] PGD 14cc0d067 
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765298] PUD 14cc07067 
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765307] PMD 0 
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765315] 
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765328] Oops: 0010 [#1] SMP
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765338] Modules linked in: rfcomm xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack libcrc32c bnep xt_tcpudp bbswitch(OE) bridge stp llc iptable_filter ip_tables x_tables 8250_dw snd_hda_codec_hdmi snd_hda_codec_realtek snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep snd_pcm snd_seq_midi snd_seq_midi_event intel_rapl x86_pkg_temp_thermal intel_powerclamp kvm irqbypass snd_rawmidi crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc snd_seq aesni_intel aes_x86_64 crypto_simd glue_helper cryptd arc4 intel_cstate snd_seq_device snd_timer intel_rapl_perf snd joydev input_leds serio_raw uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_core videodev rtl8821ae(OE)
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765570]  btcoexist(OE) rtl_pci(OE) rtlwifi(OE) mac80211 media soundcore cfg80211 mei_me idma64 virt_dma btusb intel_lpss_pci btrtl binfmt_misc mei hci_uart shpchp ideapad_laptop btbcm sparse_keymap btqca btintel bluetooth intel_pch_thermal ucsi wmi tpm_crb intel_lpss_acpi intel_lpss mac_hid acpi_pad coretemp parport_pc ppdev lp parport autofs4 hid_generic usbhid i915 psmouse i2c_algo_bit drm_kms_helper nvme nvme_core syscopyarea sysfillrect sysimgblt r8169 fb_sys_fops ahci mii drm libahci video i2c_hid pinctrl_sunrisepoint hid pinctrl_intel fjes [last unloaded: nvidia]
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765710] CPU: 0 PID: 176 Comm: kworker/u8:3 Tainted: P        W  OE   4.10.8-041008-generic #201703310531
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765735] Hardware name: LENOVO 80RU/Lenovo ideapad 700-15ISK, BIOS E5CN56WW 09/29/2016
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765775] Workqueue: phy0 ieee80211_iface_work [mac80211]
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765791] task: ffff89d50f4e0000 task.stack: ffffa66100f5c000
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765820] RIP: 0010:          (null)
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765831] RSP: 0018:ffffa66100f5fc88 EFLAGS: 00010246
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765846] RAX: ffffffffc2369620 RBX: 0000000000000000 RCX: 0000000000000000
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765864] RDX: 0000000000000000 RSI: ffffa66100f5fc97 RDI: ffff89d51c5f1520
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765882] RBP: ffffa66100f5fcb8 R08: 0000000000000000 R09: ffff89d50db46000
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765900] R10: ffff89d51c5f0720 R11: 0000000000000000 R12: ffff89d514216818
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765919] R13: ffff89d51c5f1520 R14: 00000000ffffffa1 R15: ffffa66100f5fd68
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765937] FS:  0000000000000000(0000) GS:ffff89d51ec00000(0000) knlGS:0000000000000000
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765958] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765974] CR2: 0000000000000000 CR3: 000000014cdeb000 CR4: 00000000003406f0
Apr  7 22:13:02 FeckaLaptop kernel: [   13.765992] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766011] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766028] Call Trace:
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766040]  ? rtl_rx_agg_start+0x92/0xb0 [rtlwifi]
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766055]  rtl_op_ampdu_action+0x45/0x80 [rtlwifi]
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766096]  drv_ampdu_action+0x6f/0x170 [mac80211]
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766119]  __ieee80211_start_rx_ba_session+0x395/0x610 [mac80211]
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766143]  ieee80211_process_addba_request+0x5f/0x70 [mac80211]
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766168]  ieee80211_iface_work+0x437/0x470 [mac80211]
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766184]  process_one_work+0x1fc/0x4b0
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766197]  worker_thread+0x4b/0x500
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766208]  kthread+0x101/0x140
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766218]  ? process_one_work+0x4b0/0x4b0
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766245]  ? kthread_create_on_node+0x60/0x60
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766259]  ret_from_fork+0x2c/0x40
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766269] Code:  Bad RIP value.
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766296] RIP:           (null) RSP: ffffa66100f5fc88
Apr  7 22:13:02 FeckaLaptop kernel: [   13.766330] CR2: 0000000000000000
Apr  7 22:13:02 FeckaLaptop kernel: [   13.772607] ---[ end trace a9f4ea469c6be1df ]---
Apr  7 22:13:04 FeckaLaptop kernel: [   15.602684] BUG: unable to handle kernel NULL pointer dereference at           (null)
Apr  7 22:13:04 FeckaLaptop kernel: [   15.602709] IP:           (null)
Apr  7 22:13:04 FeckaLaptop kernel: [   15.602718] PGD 0 
Apr  7 22:13:04 FeckaLaptop kernel: [   15.602719] 
Apr  7 22:13:04 FeckaLaptop kernel: [   15.602730] Oops: 0010 [#2] SMP
Apr  7 22:13:04 FeckaLaptop kernel: [   15.602739] Modules linked in: ccm rfcomm xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack libcrc32c bnep xt_tcpudp bbswitch(OE) bridge stp llc iptable_filter ip_tables x_tables 8250_dw snd_hda_codec_hdmi snd_hda_codec_realtek snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep snd_pcm snd_seq_midi snd_seq_midi_event intel_rapl x86_pkg_temp_thermal intel_powerclamp kvm irqbypass snd_rawmidi crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc snd_seq aesni_intel aes_x86_64 crypto_simd glue_helper cryptd arc4 intel_cstate snd_seq_device snd_timer intel_rapl_perf snd joydev input_leds serio_raw uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_core videodev rtl8821ae(OE)
Apr  7 22:13:04 FeckaLaptop kernel: [   15.602899]  btcoexist(OE) rtl_pci(OE) rtlwifi(OE) mac80211 media soundcore cfg80211 mei_me idma64 virt_dma btusb intel_lpss_pci btrtl binfmt_misc mei hci_uart shpchp ideapad_laptop btbcm sparse_keymap btqca btintel bluetooth intel_pch_thermal ucsi wmi tpm_crb intel_lpss_acpi intel_lpss mac_hid acpi_pad coretemp parport_pc ppdev lp parport autofs4 hid_generic usbhid i915 psmouse i2c_algo_bit drm_kms_helper nvme nvme_core syscopyarea sysfillrect sysimgblt r8169 fb_sys_fops ahci mii drm libahci video i2c_hid pinctrl_sunrisepoint hid pinctrl_intel fjes [last unloaded: nvidia]
Apr  7 22:13:04 FeckaLaptop kernel: [   15.603030] CPU: 0 PID: 33 Comm: kworker/0:1 Tainted: P      D W  OE   4.10.8-041008-generic #201703310531
Apr  7 22:13:04 FeckaLaptop kernel: [   15.603057] Hardware name: LENOVO 80RU/Lenovo ideapad 700-15ISK, BIOS E5CN56WW 09/29/2016
Apr  7 22:13:04 FeckaLaptop kernel: [   15.603080] Workqueue: rtl8821ae_pci rtl_watchdog_wq_callback [rtlwifi]
Apr  7 22:13:04 FeckaLaptop kernel: [   15.603096] task: ffff89d51d6a4500 task.stack: ffffa661007a0000
Apr  7 22:13:04 FeckaLaptop kernel: [   15.603110] RIP: 0010:          (null)
Apr  7 22:13:04 FeckaLaptop kernel: [   15.603120] RSP: 0018:ffffa661007a3de0 EFLAGS: 00010202
Apr  7 22:13:04 FeckaLaptop kernel: [   15.603133] RAX: ffffffffc2369620 RBX: ffff89d51c5f0720 RCX: 0000000000000002
Apr  7 22:13:04 FeckaLaptop kernel: [   15.603149] RDX: 0000000000000002 RSI: ffff89d51ec18a60 RDI: ffff89d51c5f1520
Apr  7 22:13:04 FeckaLaptop kernel: [   15.603165] RBP: ffffa661007a3e48 R08: 0000000000000000 R09: ffff89d51c5fb5e4
Apr  7 22:13:04 FeckaLaptop kernel: [   15.604340] R10: 0000000000000000 R11: 0000000000000000 R12: ffff89d51c5f1520
Apr  7 22:13:04 FeckaLaptop kernel: [   15.605527] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
Apr  7 22:13:04 FeckaLaptop kernel: [   15.606695] FS:  0000000000000000(0000) GS:ffff89d51ec00000(0000) knlGS:0000000000000000
Apr  7 22:13:04 FeckaLaptop kernel: [   15.607877] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Apr  7 22:13:04 FeckaLaptop kernel: [   15.609091] CR2: 0000000000000000 CR3: 000000015ba09000 CR4: 00000000003406f0
Apr  7 22:13:04 FeckaLaptop kernel: [   15.610294] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Apr  7 22:13:04 FeckaLaptop kernel: [   15.611491] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Apr  7 22:13:04 FeckaLaptop kernel: [   15.612676] Call Trace:
Apr  7 22:13:04 FeckaLaptop kernel: [   15.613803]  ? rtl_watchdog_wq_callback+0x443/0x480 [rtlwifi]
Apr  7 22:13:04 FeckaLaptop kernel: [   15.614905]  process_one_work+0x1fc/0x4b0
Apr  7 22:13:04 FeckaLaptop kernel: [   15.615988]  worker_thread+0x4b/0x500
Apr  7 22:13:04 FeckaLaptop kernel: [   15.617023]  kthread+0x101/0x140
Apr  7 22:13:04 FeckaLaptop kernel: [   15.618015]  ? process_one_work+0x4b0/0x4b0
Apr  7 22:13:04 FeckaLaptop kernel: [   15.618976]  ? kthread_create_on_node+0x60/0x60
Apr  7 22:13:04 FeckaLaptop kernel: [   15.619922]  ret_from_fork+0x2c/0x40
Apr  7 22:13:04 FeckaLaptop kernel: [   15.620855] Code:  Bad RIP value.
Apr  7 22:13:04 FeckaLaptop kernel: [   15.621791] RIP:           (null) RSP: ffffa661007a3de0
Apr  7 22:13:04 FeckaLaptop kernel: [   15.622698] CR2: 0000000000000000
Apr  7 22:13:04 FeckaLaptop kernel: [   15.623632] ---[ end trace a9f4ea469c6be1e0 ]---
```

**Comment by max7255** [comment]
Got the same issue with ubuntu 16.10 4.8.0-generic{41,45,46} kernels 

It's likely you've already discovered the following fact, but:

reverting commit 8fc5c8109ec747c4782800cd030ed933db81418b (rtlwifi_new: btcoexist: Copy btcoex routines from kernel) does the trick and kernel stops crashing after AP association.

**Comment by feckah** [comment]
Thank you! will try it asap.

**Comment by lwfinger** [comment]
I just pushed a fix for the errors introduced with commit 8fc5c81.

**Comment by feckah** [comment]
The latest commit seems to have fixed the issue, and it works like a charm now, thank you a lot again!
