### ISSUE TITLE
rtl8723ae causing High interrupts on Fedora 27 and 28

### ISSUE THREAD

**Issue by EugeneBas9** [lwfinger/rtlwifi_new#345]
Fedora 27, now 28 with latest kernel. After some time it starts taking 100% of %cpu2 until i reboot my pc. But this issue always back. Anyone know how to fix? Thanks
![photo_2018-04-05_14-19-38](https://user-images.githubusercontent.com/38143014/38441612-a466fa28-39e5-11e8-9e68-e8c9f2706b49.jpg)

**Comment by KoWu** [comment]
The msi Option just causes the System to freeze due to the interrupts queuing up. IMO the interrupts are fired because of a firmware bug. This is not a recent bug, just noone looked into his /proc/interrupts wile having the problem. Except for the Interrupts the Problem was invisible. A recent linux commit / option (idk wich) just made the high cpu usage visible. Maybe you have experienced before that your CPU did not throttle down anymore even if there was no load! That's all the same Issue. Only a reboot (poweroff of the module) resolves the Issue. I don't expect Realtek to fix this bug. If it annoys you buy an Intel card.

**Comment by lwfinger** [comment]
I just pushed an untested patch that adds the module parameter "int_clear" to the driver in the extended branch. If it is set to 1, it clears all interrupts before it sets them. I have no idea if it will help, but if something is being set that the interrupt routine is not expecting, then this should help.

**Comment by KoWu** [comment]
Nope, sadly this doesn't help either. Isn't there some kind of reset vector? Only a power-down of the module solves firing of the interrupts. Some time ago I also tested adding quite big delays to the pci read/writes because I thought about some firmware race condition but this also didn't solve the issue.
